language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t danielwyleczukstern/docker-react .

script:
  - docker run -e CI=true danielwyleczukstern/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-748184668625"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"